"""Infrastructure shared by autoregressive and diffusion language models.

Subpackages separate the concerns that experiments assemble:
``sampling`` (algorithm kernels), ``budget`` (compute allocation),
``model`` (loading, prompting, generation limits, output parsing),
``rewards`` (verifiers and Consilience arithmetic) and ``evaluation``
(benchmarks and answer checking).
"""

from inference_scaling.shared.budget import (
    BudgetAllocation,
    VarianceCostEstimate,
    allocate_fresh_rollout_budget,
    allocate_variance_cost_budget,
)
from inference_scaling.shared.config import RuntimeConfig, SMCForestConfig
from inference_scaling.shared.rng import SeedStream
from inference_scaling.shared.sampling import (
    MetropolisHastingsDecision,
    MetropolisHastingsProposal,
    MetropolisHastingsTransition,
    MonteCarloRolloutWeightProvider,
    MonteCarloWeightEstimate,
    ProbabilityObservation,
    ReplayWeightEstimate,
    RolloutObservation,
    TruncatedReplayRolloutWeightProvider,
    WeightedRollout,
    apply_metropolis_hastings,
    corrected_replay_log_weight,
    decide_metropolis_hastings,
    logmeanexp,
    metropolis_hastings_log_acceptance,
    normalize_smc_log_weights,
    partition_resampled_reservoirs,
    systematic_resample,
    StepwiseCandidate,
    StepwiseGenerationBackend,
    StepwiseGenerationResult,
    StepwiseSelection,
    categorical_index_from_uniform,
    normalize_log_weights,
    run_stepwise_generation,
    select_stepwise_candidate,
    stepwise_generation_step,
)
from inference_scaling.shared.types import TokenSequence
from inference_scaling.shared.rewards import (
    ConfiguredTrainingVerifierReward,
    ConfiguredVerifier,
    TokenBatchReward,
    TokenReward,
    TokenVerifierReward,
    VerifierContext,
    VerifierInput,
    VerifierSpec,
    build_token_verifier_reward,
    build_verifier,
)

__all__ = [
    "BudgetAllocation",
    "ConfiguredTrainingVerifierReward",
    "ConfiguredVerifier",
    "VarianceCostEstimate",
    "SMCForestConfig",
    "MetropolisHastingsDecision",
    "MetropolisHastingsProposal",
    "MetropolisHastingsTransition",
    "MonteCarloWeightEstimate",
    "MonteCarloRolloutWeightProvider",
    "ProbabilityObservation",
    "ReplayWeightEstimate",
    "RolloutObservation",
    "StepwiseCandidate",
    "StepwiseGenerationBackend",
    "StepwiseGenerationResult",
    "StepwiseSelection",
    "TruncatedReplayRolloutWeightProvider",
    "WeightedRollout",
    "RuntimeConfig",
    "SeedStream",
    "TokenSequence",
    "TokenBatchReward",
    "TokenReward",
    "TokenVerifierReward",
    "VerifierContext",
    "VerifierInput",
    "VerifierSpec",
    "apply_metropolis_hastings",
    "allocate_fresh_rollout_budget",
    "allocate_variance_cost_budget",
    "build_token_verifier_reward",
    "build_verifier",
    "corrected_replay_log_weight",
    "categorical_index_from_uniform",
    "logmeanexp",
    "metropolis_hastings_log_acceptance",
    "normalize_log_weights",
    "normalize_smc_log_weights",
    "partition_resampled_reservoirs",
    "decide_metropolis_hastings",
    "run_stepwise_generation",
    "select_stepwise_candidate",
    "stepwise_generation_step",
    "systematic_resample",
]
